import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      // REMOVE ALL BORDER RADIUS - BRUTAL RECTANGLES ONLY
      borderRadius: {
        DEFAULT: '0',
        none: '0',
        sm: '0',
        md: '0',
        lg: '0',
        xl: '0',
        '2xl': '0',
        '3xl': '0',
        full: '0',
      },
      // BRUTAL NOIR SHADOW SYSTEM
      boxShadow: {
        none: 'none',
        // Angular noir shadows at 45 degrees
        'noir-sm': '5px 5px 0px rgba(0, 0, 0, 1)',
        'noir-md': '10px 10px 0px rgba(0, 0, 0, 1)',
        'noir-lg': '15px 15px 0px rgba(0, 0, 0, 1), 20px 20px 20px rgba(0, 0, 0, 0.8)',
        'noir-xl': '20px 20px 0px rgba(0, 0, 0, 1), 30px 30px 30px rgba(0, 0, 0, 0.7)',
        'noir-2xl': '30px 30px 0px rgba(0, 0, 0, 1), 40px 40px 40px rgba(0, 0, 0, 0.6)',
        // Dramatic layered shadows
        'brutal': '10px 10px 20px rgba(0, 0, 0, 0.9), 20px 20px 40px rgba(0, 0, 0, 0.7)',
        'blood': '10px 10px 20px rgba(139, 0, 0, 0.9), 20px 20px 40px rgba(139, 0, 0, 0.5)',
        'void': '0px 0px 30px rgba(0, 0, 0, 1) inset',
        // Override defaults with noir shadows
        sm: '5px 5px 0px rgba(0, 0, 0, 1)',
        DEFAULT: '10px 10px 0px rgba(0, 0, 0, 1)',
        md: '10px 10px 0px rgba(0, 0, 0, 1)',
        lg: '15px 15px 0px rgba(0, 0, 0, 1)',
        xl: '20px 20px 0px rgba(0, 0, 0, 1)',
        '2xl': '30px 30px 0px rgba(0, 0, 0, 1)',
        inner: '0px 0px 30px rgba(0, 0, 0, 1) inset',
      },
      colors: {
        // Flat / base colors (regular buttons)
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        border: "hsl(var(--border) / <alpha-value>)",
        input: "hsl(var(--input) / <alpha-value>)",
        card: {
          DEFAULT: "hsl(var(--card) / <alpha-value>)",
          foreground: "hsl(var(--card-foreground) / <alpha-value>)",
          border: "hsl(var(--card-border) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "hsl(var(--popover) / <alpha-value>)",
          foreground: "hsl(var(--popover-foreground) / <alpha-value>)",
          border: "hsl(var(--popover-border) / <alpha-value>)",
        },
        primary: {
          DEFAULT: "hsl(var(--primary) / <alpha-value>)",
          foreground: "hsl(var(--primary-foreground) / <alpha-value>)",
          border: "var(--primary-border)",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary) / <alpha-value>)",
          foreground: "hsl(var(--secondary-foreground) / <alpha-value>)",
          border: "var(--secondary-border)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted) / <alpha-value>)",
          foreground: "hsl(var(--muted-foreground) / <alpha-value>)",
          border: "var(--muted-border)",
        },
        accent: {
          DEFAULT: "hsl(var(--accent) / <alpha-value>)",
          foreground: "hsl(var(--accent-foreground) / <alpha-value>)",
          border: "var(--accent-border)",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
          border: "var(--destructive-border)",
        },
        ring: "hsl(var(--ring) / <alpha-value>)",
        chart: {
          "1": "hsl(var(--chart-1) / <alpha-value>)",
          "2": "hsl(var(--chart-2) / <alpha-value>)",
          "3": "hsl(var(--chart-3) / <alpha-value>)",
          "4": "hsl(var(--chart-4) / <alpha-value>)",
          "5": "hsl(var(--chart-5) / <alpha-value>)",
        },
        sidebar: {
          ring: "hsl(var(--sidebar-ring) / <alpha-value>)",
          DEFAULT: "hsl(var(--sidebar) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-foreground) / <alpha-value>)",
          border: "hsl(var(--sidebar-border) / <alpha-value>)",
        },
        "sidebar-primary": {
          DEFAULT: "hsl(var(--sidebar-primary) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-primary-foreground) / <alpha-value>)",
          border: "var(--sidebar-primary-border)",
        },
        "sidebar-accent": {
          DEFAULT: "hsl(var(--sidebar-accent) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-accent-foreground) / <alpha-value>)",
          border: "var(--sidebar-accent-border)"
        },
        status: {
          online: "rgb(34 197 94)",
          away: "rgb(245 158 11)",
          busy: "rgb(239 68 68)",
          offline: "rgb(156 163 175)",
        },
        // Seven Houses - all converted to noir palette
        "house-heroes": {
          DEFAULT: "hsl(var(--house-heroes-primary) / <alpha-value>)",
          foreground: "hsl(var(--house-heroes-primary-foreground) / <alpha-value>)",
          secondary: "hsl(var(--house-heroes-secondary) / <alpha-value>)",
          accent: "hsl(var(--house-heroes-accent) / <alpha-value>)",
          background: "hsl(var(--house-heroes-background) / <alpha-value>)",
          card: "hsl(var(--house-heroes-card) / <alpha-value>)",
          border: "var(--house-heroes-primary-border)",
        },
        "house-wisdom": {
          DEFAULT: "hsl(var(--house-wisdom-primary) / <alpha-value>)",
          foreground: "hsl(var(--house-wisdom-primary-foreground) / <alpha-value>)",
          secondary: "hsl(var(--house-wisdom-secondary) / <alpha-value>)",
          accent: "hsl(var(--house-wisdom-accent) / <alpha-value>)",
          background: "hsl(var(--house-wisdom-background) / <alpha-value>)",
          card: "hsl(var(--house-wisdom-card) / <alpha-value>)",
          border: "var(--house-wisdom-primary-border)",
        },
        "house-power": {
          DEFAULT: "hsl(var(--house-power-primary) / <alpha-value>)",
          foreground: "hsl(var(--house-power-primary-foreground) / <alpha-value>)",
          secondary: "hsl(var(--house-power-secondary) / <alpha-value>)",
          accent: "hsl(var(--house-power-accent) / <alpha-value>)",
          background: "hsl(var(--house-power-background) / <alpha-value>)",
          card: "hsl(var(--house-power-card) / <alpha-value>)",
          border: "var(--house-power-primary-border)",
        },
        "house-mystery": {
          DEFAULT: "hsl(var(--house-mystery-primary) / <alpha-value>)",
          foreground: "hsl(var(--house-mystery-primary-foreground) / <alpha-value>)",
          secondary: "hsl(var(--house-mystery-secondary) / <alpha-value>)",
          accent: "hsl(var(--house-mystery-accent) / <alpha-value>)",
          background: "hsl(var(--house-mystery-background) / <alpha-value>)",
          card: "hsl(var(--house-mystery-card) / <alpha-value>)",
          border: "var(--house-mystery-primary-border)",
        },
        "house-elements": {
          DEFAULT: "hsl(var(--house-elements-primary) / <alpha-value>)",
          foreground: "hsl(var(--house-elements-primary-foreground) / <alpha-value>)",
          secondary: "hsl(var(--house-elements-secondary) / <alpha-value>)",
          accent: "hsl(var(--house-elements-accent) / <alpha-value>)",
          background: "hsl(var(--house-elements-background) / <alpha-value>)",
          card: "hsl(var(--house-elements-card) / <alpha-value>)",
          border: "var(--house-elements-primary-border)",
        },
        "house-time": {
          DEFAULT: "hsl(var(--house-time-primary) / <alpha-value>)",
          foreground: "hsl(var(--house-time-primary-foreground) / <alpha-value>)",
          secondary: "hsl(var(--house-time-secondary) / <alpha-value>)",
          accent: "hsl(var(--house-time-accent) / <alpha-value>)",
          background: "hsl(var(--house-time-background) / <alpha-value>)",
          card: "hsl(var(--house-time-card) / <alpha-value>)",
          border: "var(--house-time-primary-border)",
        },
        "house-spirit": {
          DEFAULT: "hsl(var(--house-spirit-primary) / <alpha-value>)",
          foreground: "hsl(var(--house-spirit-primary-foreground) / <alpha-value>)",
          secondary: "hsl(var(--house-spirit-secondary) / <alpha-value>)",
          accent: "hsl(var(--house-spirit-accent) / <alpha-value>)",
          background: "hsl(var(--house-spirit-background) / <alpha-value>)",
          card: "hsl(var(--house-spirit-card) / <alpha-value>)",
          border: "var(--house-spirit-primary-border)",
        },
      },
      fontFamily: {
        // Heavy brutal fonts
        sans: ['Space Grotesk', 'system-ui', 'sans-serif'],
        display: ['Oswald', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      fontWeight: {
        light: '400',
        normal: '500',
        medium: '600',
        semibold: '700',
        bold: '800',
        extrabold: '900',
      },
      letterSpacing: {
        tighter: '0',
        tight: '0.02em',
        normal: '0.05em',
        wide: '0.1em',
        wider: '0.15em',
        widest: '0.2em',
      },
      // Remove all smooth transitions
      transitionDuration: {
        DEFAULT: '0ms',
        '0': '0ms',
        '75': '0ms',
        '100': '0ms',
        '150': '0ms',
        '200': '0ms',
        '300': '0ms',
        '500': '0ms',
        '700': '0ms',
        '1000': '0ms',
      },
      transitionTimingFunction: {
        DEFAULT: 'linear',
        linear: 'linear',
        in: 'linear',
        out: 'linear',
        'in-out': 'linear',
      },
      // Brutal spacing for oppressive negative space
      spacing: {
        'void': '4rem',
        'dread': '6rem',
        'abyss': '8rem',
        'chasm': '10rem',
      },
      borderWidth: {
        DEFAULT: '2px',
        '0': '0',
        '2': '2px',
        '3': '3px',
        '4': '4px',
        '6': '6px',
        '8': '8px',
        'brutal': '4px',
        'stark': '3px',
        'heavy': '2px',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;