import { Character } from '../types';

// All Characters Data
export const allCharacters: Character[] = [
  {
    id: '1',
    name: 'Spider-Man',
    symbol: 'SPDR',
    characterType: 'hero',
    price: 7200,
    change: 381.60,
    percentageChange: 5.3,
    marketCap: 360000000,
    volume: 3500,
    rating: 'Strong Buy',
    firstAppearance: 'Amazing Fantasy #15 (1962)',
    publisher: 'Marvel',
    powers: ['Wall-crawling', 'Spider-sense', 'Super strength', 'Web-slinging', 'Agility', 'Reflexes'],
    nemesis: 'Green Goblin',
    allies: ['Mary Jane Watson', 'Aunt May', 'Gwen Stacy', 'Miles Morales', 'Spider-Woman'],
    popularity: 98,
    mediaAppearances: 45,
    description: 'The friendly neighborhood Spider-Man, one of Marvel\'s most iconic and beloved superheroes.',
    avatar: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?w=150&h=150&fit=crop'
  },
  {
    id: '2',
    name: 'Batman',
    symbol: 'BATM',
    characterType: 'hero',
    price: 68,
    change: 4,
    percentageChange: 5.3,
    marketCap: 3400000,
    volume: 3200,
    rating: 'Strong Buy',
    firstAppearance: 'Detective Comics #27 (1939)',
    publisher: 'DC',
    powers: ['Martial arts mastery', 'Detective skills', 'Advanced technology', 'Peak human condition', 'Strategic genius', 'Intimidation'],
    nemesis: 'The Joker',
    allies: ['Robin', 'Alfred Pennyworth', 'Commissioner Gordon', 'Batgirl', 'Nightwing'],
    popularity: 99,
    mediaAppearances: 52,
    description: 'The Dark Knight of Gotham City, a symbol of justice and determination.',
    avatar: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=150&h=150&fit=crop'
  },
  {
    id: '3',
    name: 'Superman',
    symbol: 'SUPR',
    characterType: 'hero',
    price: 64,
    change: 3,
    percentageChange: 5.3,
    marketCap: 3200000,
    volume: 3800,
    rating: 'Strong Buy',
    firstAppearance: 'Action Comics #1 (1938)',
    publisher: 'DC',
    powers: ['Super strength', 'Flight', 'Invulnerability', 'Heat vision', 'X-ray vision', 'Super speed'],
    nemesis: 'Lex Luthor',
    allies: ['Lois Lane', 'Jimmy Olsen', 'Batman', 'Wonder Woman', 'Justice League'],
    popularity: 99,
    mediaAppearances: 48,
    description: 'The Man of Steel, Earth\'s greatest protector and symbol of hope.',
    avatar: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=150&h=150&fit=crop'
  },
  {
    id: '4',
    name: 'The Joker',
    symbol: 'JOKR',
    characterType: 'villain',
    price: 55,
    change: -1,
    percentageChange: -2.0,
    marketCap: 2750000,
    volume: 2800,
    rating: 'Buy',
    firstAppearance: 'Batman #1 (1940)',
    publisher: 'DC',
    powers: ['Criminal genius', 'Unpredictability', 'Chemical immunity', 'Madness', 'Manipulation', 'Fear tactics'],
    nemesis: 'Batman',
    allies: ['Harley Quinn', 'Penguin', 'Two-Face', 'Riddler'],
    popularity: 95,
    mediaAppearances: 38,
    description: 'The Clown Prince of Crime, Batman\'s greatest and most unpredictable foe.',
    avatar: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop'
  },
  {
    id: '5',
    name: 'Wonder Woman',
    symbol: 'WNDR',
    characterType: 'hero',
    price: 58,
    change: 3,
    percentageChange: 5.3,
    marketCap: 2900000,
    volume: 2900,
    rating: 'Strong Buy',
    firstAppearance: 'All Star Comics #8 (1941)',
    publisher: 'DC',
    powers: ['Super strength', 'Flight', 'Lasso of Truth', 'Bracelets of Submission', 'Combat expertise', 'Divine powers'],
    nemesis: 'Cheetah',
    allies: ['Steve Trevor', 'Hippolyta', 'Batman', 'Superman', 'Justice League'],
    popularity: 94,
    mediaAppearances: 35,
    description: 'Princess Diana of Themyscira, an Amazon warrior and advocate for peace and justice.',
    avatar: 'https://images.unsplash.com/photo-1594736797933-d0902ba2fe65?w=150&h=150&fit=crop'
  },
  // Sidekicks
  {
    id: '6',
    name: 'Robin (Dick Grayson)',
    symbol: 'RBDN',
    characterType: 'sidekick',
    price: 22,
    change: 1,
    percentageChange: 5.3,
    marketCap: 1100000,
    volume: 1800,
    rating: 'Buy',
    firstAppearance: 'Detective Comics #38 (1940)',
    publisher: 'DC',
    powers: ['Acrobatics', 'Martial arts', 'Detective skills', 'Leadership', 'Gadgets', 'Stealth'],
    nemesis: 'Two-Face',
    allies: ['Batman', 'Nightwing', 'Teen Titans', 'Barbara Gordon'],
    popularity: 88,
    mediaAppearances: 32,
    description: 'The first Robin, now known as Nightwing, Dick Grayson was Batman\'s original partner.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop'
  },
  {
    id: '7',
    name: 'Robin (Tim Drake)',
    symbol: 'RBNT',
    characterType: 'sidekick',
    price: 18,
    change: 1,
    percentageChange: 5.3,
    marketCap: 900000,
    volume: 1400,
    rating: 'Buy',
    firstAppearance: 'Batman #436 (1989)',
    publisher: 'DC',
    powers: ['Detective skills', 'Martial arts', 'Computer expertise', 'Acrobatics', 'Strategic planning', 'Technology'],
    allies: ['Batman', 'Red Robin', 'Young Justice', 'Teen Titans'],
    popularity: 82,
    mediaAppearances: 28,
    description: 'The third Robin, Tim Drake brought detective skills and technological expertise to the role.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop'
  },
  // Henchmen
  {
    id: '8',
    name: 'Harley Quinn',
    symbol: 'HRLY',
    characterType: 'henchman',
    price: 28,
    change: 1,
    percentageChange: 5.3,
    marketCap: 1400000,
    volume: 2200,
    rating: 'Strong Buy',
    firstAppearance: 'Batman: The Animated Series (1992)',
    publisher: 'DC',
    powers: ['Gymnastics', 'Combat skills', 'Unpredictability', 'Resistance to toxins', 'Agility', 'Weapon expertise'],
    nemesis: 'Batman',
    allies: ['The Joker', 'Poison Ivy', 'Catwoman', 'Birds of Prey'],
    popularity: 93,
    mediaAppearances: 35,
    description: 'Former psychiatrist turned chaotic anti-hero, known for her unpredictable nature and acrobatic skills.',
    avatar: 'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=150&h=150&fit=crop'
  },
  // Additional Heroes to reach 350+ assets
  {
    id: '9',
    name: 'Iron Man',
    symbol: 'IRNM',
    characterType: 'hero',
    price: 61,
    change: 3,
    percentageChange: 5.2,
    marketCap: 3050000,
    volume: 3100,
    rating: 'Strong Buy',
    firstAppearance: 'Tales of Suspense #39 (1963)',
    publisher: 'Marvel',
    powers: ['Powered armor', 'Flight', 'Repulsors', 'AI assistance', 'Engineering genius', 'Arc reactor'],
    allies: ['Pepper Potts', 'War Machine', 'Avengers'],
    popularity: 96,
    mediaAppearances: 42,
    description: 'Genius inventor Tony Stark in his high-tech powered armor.',
    avatar: 'https://images.unsplash.com/photo-1605117882932-f9e32b03fea9?w=150&h=150&fit=crop'
  },
  {
    id: '10',
    name: 'Captain America',
    symbol: 'CAPA',
    characterType: 'hero',
    price: 59,
    change: 3,
    percentageChange: 5.4,
    marketCap: 2950000,
    volume: 2800,
    rating: 'Strong Buy',
    firstAppearance: 'Captain America Comics #1 (1941)',
    publisher: 'Marvel',
    powers: ['Enhanced strength', 'Shield mastery', 'Leadership', 'Tactical genius', 'Peak human condition', 'Vibranium shield'],
    allies: ['Bucky Barnes', 'Falcon', 'Avengers'],
    popularity: 92,
    mediaAppearances: 38,
    description: 'Super-soldier Steve Rogers, the First Avenger and symbol of freedom.',
    avatar: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop'
  },
  {
    id: '11',
    name: 'Hulk',
    symbol: 'HULK',
    characterType: 'hero',
    price: 56,
    change: 3,
    percentageChange: 5.7,
    marketCap: 2800000,
    volume: 2600,
    rating: 'Buy',
    firstAppearance: 'The Incredible Hulk #1 (1962)',
    publisher: 'Marvel',
    powers: ['Super strength', 'Invulnerability', 'Regeneration', 'Limitless strength potential', 'Gamma immunity'],
    nemesis: 'Abomination',
    allies: ['Bruce Banner', 'Avengers', 'Rick Jones'],
    popularity: 89,
    mediaAppearances: 35,
    description: 'Dr. Bruce Banner transforms into the incredible Hulk when angry.',
    avatar: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=150&h=150&fit=crop'
  },
  {
    id: '12',
    name: 'Thor',
    symbol: 'THOR',
    characterType: 'hero',
    price: 54,
    change: 3,
    percentageChange: 5.9,
    marketCap: 2700000,
    volume: 2400,
    rating: 'Buy',
    firstAppearance: 'Journey into Mystery #83 (1962)',
    publisher: 'Marvel',
    powers: ['Godly strength', 'Mjolnir mastery', 'Weather control', 'Flight', 'Lightning', 'Immortality'],
    allies: ['Loki', 'Odin', 'Avengers', 'Jane Foster'],
    popularity: 88,
    mediaAppearances: 32,
    description: 'Asgardian God of Thunder and member of the Avengers.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop'
  },
  {
    id: '13',
    name: 'Flash',
    symbol: 'FLSH',
    characterType: 'hero',
    price: 48,
    change: 2,
    percentageChange: 4.3,
    marketCap: 2400000,
    volume: 2200,
    rating: 'Buy',
    firstAppearance: 'Flash Comics #1 (1940)',
    publisher: 'DC',
    powers: ['Super speed', 'Time travel', 'Vibration phasing', 'Speed force', 'Lightning generation'],
    nemesis: 'Reverse-Flash',
    allies: ['Justice League', 'Kid Flash', 'Jay Garrick'],
    popularity: 85,
    mediaAppearances: 28,
    description: 'The Fastest Man Alive, protector of Central City.',
    avatar: 'https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=150&h=150&fit=crop'
  },
  {
    id: '14',
    name: 'Green Lantern',
    symbol: 'GRLN',
    characterType: 'hero',
    price: 45,
    change: 2,
    percentageChange: 4.7,
    marketCap: 2250000,
    volume: 2000,
    rating: 'Buy',
    firstAppearance: 'All-American Comics #16 (1940)',
    publisher: 'DC',
    powers: ['Power ring', 'Constructs', 'Flight', 'Force fields', 'Energy projection', 'Space travel'],
    allies: ['Green Lantern Corps', 'Justice League'],
    popularity: 82,
    mediaAppearances: 25,
    description: 'Intergalactic peacekeepers wielding the power of will.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop'
  },
  {
    id: '15',
    name: 'Aquaman',
    symbol: 'AQMN',
    characterType: 'hero',
    price: 42,
    change: 2,
    percentageChange: 5.0,
    marketCap: 2100000,
    volume: 1800,
    rating: 'Buy',
    firstAppearance: 'More Fun Comics #73 (1941)',
    publisher: 'DC',
    powers: ['Underwater breathing', 'Super strength', 'Marine telepathy', 'Trident mastery', 'Swimming speed'],
    allies: ['Mera', 'Justice League', 'Atlanteans'],
    popularity: 78,
    mediaAppearances: 22,
    description: 'King of Atlantis and protector of the seven seas.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop'
  },
  {
    id: '16',
    name: 'Wolverine',
    symbol: 'WLVR',
    characterType: 'hero',
    price: 62,
    change: 3,
    percentageChange: 5.1,
    marketCap: 3100000,
    volume: 2900,
    rating: 'Strong Buy',
    firstAppearance: 'The Incredible Hulk #181 (1974)',
    publisher: 'Marvel',
    powers: ['Adamantium claws', 'Healing factor', 'Enhanced senses', 'Berserker rage', 'Longevity'],
    nemesis: 'Sabretooth',
    allies: ['X-Men', 'Avengers', 'Jean Grey'],
    popularity: 94,
    mediaAppearances: 40,
    description: 'The best there is at what he does, but what he does isn\'t very nice.',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop'
  },
  {
    id: '17',
    name: 'Deadpool',
    symbol: 'DDPL',
    characterType: 'hero',
    price: 51,
    change: 3,
    percentageChange: 6.2,
    marketCap: 2550000,
    volume: 2500,
    rating: 'Strong Buy',
    firstAppearance: 'The New Mutants #98 (1991)',
    publisher: 'Marvel',
    powers: ['Healing factor', 'Combat expertise', 'Breaking fourth wall', 'Weaponry mastery', 'Immortality'],
    allies: ['X-Force', 'Cable', 'Domino'],
    popularity: 91,
    mediaAppearances: 18,
    description: 'The Merc with a Mouth, known for his irreverent humor and brutal efficiency.',
    avatar: 'https://images.unsplash.com/photo-1528892952291-009c663ce843?w=150&h=150&fit=crop'
  },
  {
    id: '18',
    name: 'Black Panther',
    symbol: 'BLKP',
    characterType: 'hero',
    price: 63,
    change: 3,
    percentageChange: 5.0,
    marketCap: 3150000,
    volume: 2700,
    rating: 'Strong Buy',
    firstAppearance: 'Fantastic Four #52 (1966)',
    publisher: 'Marvel',
    powers: ['Vibranium suit', 'Enhanced strength', 'Stealth', 'Tactical genius', 'Wakandan technology'],
    allies: ['Avengers', 'Shuri', 'Okoye', 'Nakia'],
    popularity: 90,
    mediaAppearances: 15,
    description: 'King of Wakanda and protector of his people.',
    avatar: 'https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=150&h=150&fit=crop'
  },
  {
    id: '19',
    name: 'Scarlet Witch',
    symbol: 'SCWT',
    characterType: 'hero',
    price: 49,
    change: 2,
    percentageChange: 4.3,
    marketCap: 2450000,
    volume: 2300,
    rating: 'Buy',
    firstAppearance: 'The X-Men #4 (1964)',
    publisher: 'Marvel',
    powers: ['Reality manipulation', 'Chaos magic', 'Telekinesis', 'Energy projection', 'Probability alteration'],
    allies: ['Vision', 'Avengers', 'Quicksilver'],
    popularity: 87,
    mediaAppearances: 20,
    description: 'Powerful mutant with reality-altering chaos magic abilities.',
    avatar: 'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=150&h=150&fit=crop'
  },
  {
    id: '20',
    name: 'Doctor Strange',
    symbol: 'DRST',
    characterType: 'hero',
    price: 47,
    change: 2,
    percentageChange: 4.4,
    marketCap: 2350000,
    volume: 2100,
    rating: 'Buy',
    firstAppearance: 'Strange Tales #110 (1963)',
    publisher: 'Marvel',
    powers: ['Mystic arts', 'Dimensional travel', 'Time manipulation', 'Astral projection', 'Energy shields'],
    allies: ['Wong', 'Ancient One', 'Avengers'],
    popularity: 84,
    mediaAppearances: 18,
    description: 'Master of the Mystic Arts and Sorcerer Supreme.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop'
  }
  ,
  {
    id: '21',
    name: 'Captain Marvel',
    symbol: 'CMVL',
    characterType: 'hero',
    price: 52,
    change: 2,
    percentageChange: 4.0,
    marketCap: 2600000,
    volume: 2300,
    rating: 'Buy',
    firstAppearance: 'Marvel Super-Heroes #13 (1968)',
    publisher: 'Marvel',
    powers: ['Energy projection', 'Flight', 'Super strength', 'Photon blasts', 'Energy absorption'],
    allies: ['Avengers', 'Alpha Flight', 'Monica Rambeau'],
    popularity: 86,
    mediaAppearances: 12,
    description: 'Carol Danvers, a former Air Force pilot with cosmic powers.',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop'
  },
  {
    id: '22',
    name: 'Iron Fist',
    symbol: 'IRFT',
    characterType: 'hero',
    price: 35,
    change: 1,
    percentageChange: 2.9,
    marketCap: 1750000,
    volume: 1500,
    rating: 'Hold',
    firstAppearance: 'Marvel Premiere #15 (1974)',
    publisher: 'Marvel',
    powers: ['Iron Fist', 'Martial arts mastery', 'Chi manipulation', 'Enhanced healing'],
    allies: ['Luke Cage', 'Defenders', 'Misty Knight'],
    popularity: 72,
    mediaAppearances: 8,
    description: 'Danny Rand, master of the mystical Iron Fist.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop'
  },
  {
    id: '23',
    name: 'Luke Cage',
    symbol: 'LCGE',
    characterType: 'hero',
    price: 38,
    change: 1,
    percentageChange: 2.7,
    marketCap: 1900000,
    volume: 1600,
    rating: 'Hold',
    firstAppearance: 'Luke Cage: Hero for Hire #1 (1972)',
    publisher: 'Marvel',
    powers: ['Unbreakable skin', 'Super strength', 'Enhanced stamina', 'Accelerated healing'],
    allies: ['Iron Fist', 'Defenders', 'Jessica Jones'],
    popularity: 74,
    mediaAppearances: 10,
    description: 'Power Man with unbreakable skin and super strength.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop'
  },
  {
    id: '24',
    name: 'Daredevil',
    symbol: 'DRDV',
    characterType: 'hero',
    price: 46,
    change: 2,
    percentageChange: 4.5,
    marketCap: 2300000,
    volume: 2000,
    rating: 'Buy',
    firstAppearance: 'Daredevil #1 (1964)',
    publisher: 'Marvel',
    powers: ['Radar sense', 'Enhanced agility', 'Martial arts', 'Acrobatics'],
    nemesis: 'Kingpin',
    allies: ['Elektra', 'Foggy Nelson', 'Karen Page'],
    popularity: 81,
    mediaAppearances: 15,
    description: 'The Man Without Fear, Hell\'s Kitchen\'s protector.',
    avatar: 'https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=150&h=150&fit=crop'
  },
  {
    id: '25',
    name: 'Punisher',
    symbol: 'PNSH',
    characterType: 'hero',
    price: 41,
    change: 1,
    percentageChange: 2.5,
    marketCap: 2050000,
    volume: 1800,
    rating: 'Hold',
    firstAppearance: 'The Amazing Spider-Man #129 (1974)',
    publisher: 'Marvel',
    powers: ['Expert marksman', 'Military tactics', 'Weapons expertise', 'Combat skills'],
    allies: ['Microchip', 'Nick Fury'],
    popularity: 78,
    mediaAppearances: 12,
    description: 'Frank Castle, vigilante seeking justice through lethal means.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop'
  },
  {
    id: '26',
    name: 'Ghost Rider',
    symbol: 'GHST',
    characterType: 'hero',
    price: 39,
    change: 1,
    percentageChange: 2.6,
    marketCap: 1950000,
    volume: 1700,
    rating: 'Hold',
    firstAppearance: 'Marvel Spotlight #5 (1972)',
    publisher: 'Marvel',
    powers: ['Hellfire', 'Penance Stare', 'Supernatural strength', 'Motorcycle transformation'],
    nemesis: 'Mephisto',
    allies: ['Doctor Strange', 'Midnight Sons'],
    popularity: 76,
    mediaAppearances: 8,
    description: 'Johnny Blaze, the Spirit of Vengeance.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop'
  },
  {
    id: '27',
    name: 'Silver Surfer',
    symbol: 'SLVR',
    characterType: 'hero',
    price: 44,
    change: 2,
    percentageChange: 4.8,
    marketCap: 2200000,
    volume: 1900,
    rating: 'Buy',
    firstAppearance: 'Fantastic Four #48 (1966)',
    publisher: 'Marvel',
    powers: ['Cosmic power', 'Flight', 'Energy manipulation', 'Matter transmutation'],
    nemesis: 'Galactus',
    allies: ['Fantastic Four', 'Nova Corps'],
    popularity: 79,
    mediaAppearances: 6,
    description: 'Norrin Radd, herald of Galactus turned protector.',
    avatar: 'https://images.unsplash.com/photo-1528892952291-009c663ce843?w=150&h=150&fit=crop'
  },
  {
    id: '28',
    name: 'Fantastic Four (Team)',
    symbol: 'FF4T',
    characterType: 'hero',
    price: 95,
    change: 4,
    percentageChange: 4.4,
    marketCap: 4750000,
    volume: 3500,
    rating: 'Strong Buy',
    firstAppearance: 'Fantastic Four #1 (1961)',
    publisher: 'Marvel',
    powers: ['Team synergy', 'Combined powers', 'Scientific knowledge', 'Space exploration'],
    allies: ['Avengers', 'Silver Surfer', 'Inhumans'],
    popularity: 88,
    mediaAppearances: 18,
    description: 'Marvel\'s first family of superheroes.',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop'
  },
  {
    id: '29',
    name: 'X-Men (Team)',
    symbol: 'XMNT',
    characterType: 'hero',
    price: 105,
    change: 5,
    percentageChange: 5.0,
    marketCap: 5250000,
    volume: 4000,
    rating: 'Strong Buy',
    firstAppearance: 'X-Men #1 (1963)',
    publisher: 'Marvel',
    powers: ['Mutant abilities', 'Team coordination', 'Diverse powers', 'Unity'],
    allies: ['Professor X', 'X-Factor', 'X-Force'],
    popularity: 92,
    mediaAppearances: 25,
    description: 'The uncanny X-Men, protectors of mutant rights.',
    avatar: 'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=150&h=150&fit=crop'
  },
  {
    id: '30',
    name: 'Avengers (Team)',
    symbol: 'AVNG',
    characterType: 'hero',
    price: 125,
    change: 6,
    percentageChange: 5.1,
    marketCap: 6250000,
    volume: 4500,
    rating: 'Strong Buy',
    firstAppearance: 'Avengers #1 (1963)',
    publisher: 'Marvel',
    powers: ['Earth\'s Mightiest Heroes', 'Combined might', 'Leadership', 'Unity'],
    allies: ['S.H.I.E.L.D.', 'Nick Fury', 'Captain Marvel'],
    popularity: 96,
    mediaAppearances: 35,
    description: 'Earth\'s Mightiest Heroes assembled.',
    avatar: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=150&h=150&fit=crop'
  }
]; // No comma here

// Filter by character type
export const heroes = allCharacters.filter(char => char.characterType === 'hero');
export const villains = allCharacters.filter(char => char.characterType === 'villain');
export const sidekicks = allCharacters.filter(char => char.characterType === 'sidekick');
export const henchmen = allCharacters.filter(char => char.characterType === 'henchman');

export default allCharacters;